# Generated by Django 5.0.6 on 2024-05-14 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("door_lock", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doorlock",
            name="password",
        ),
    ]
